config/routes.rb
Rails.application.routes.draw do
  get 'recruiters/index'
  get 'recruiters/show'
  get 'candidates/index'
  devise_for :admins
  devise_for :recruiters
  devise_for :candidates

  resources :candidates
  resources :companies
  resources :jobs
  resources :job_applications
  resources :notes
  resources :recruiters
  resources :tickets

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/company.rb
class Company < ApplicationRecord
  attr_accessor :is_dummy
  has_many :jobs, dependent: :destroy
  has_many :job_applications, dependent: :destroy
  has_many :recruiters, dependent: :destroy
  has_many :candidates, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_one_attached :avatar
  validates :name, :employees_count, :website, :location, :currency, presence: true
  after_commit :set_avatar, on: [:create, :update]

  private
  def set_avatar
    unless avatar.attached? || is_dummy
      image = File.open(Rails.root.join("app", "assets", "images", "avatar.png"))
      avatar.attach(io: image, filename: "avatar.png" , content_type: "image/png")
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: " company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :subscribed, :plan, :description, :employees_count, :website, :location, :hidden, :currency, :subdomain)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div >
  <p class="my-5">
    <strong class="block mb-1 font-medium">Name:</strong>
    <%= company.name %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Subscribed:</strong>
    <%= company.subscribed %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Plan:</strong>
    <%= company.plan %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Description:</strong>
    <%= company.description %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Employees count:</strong>
    <%= company.employees_count %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Website:</strong>
    <%= company.website %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Location:</strong>
    <%= company.location %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Hidden:</strong>
    <%= company.hidden %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Currency:</strong>
    <%= company.currency %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Subdomain:</strong>
    <%= company.subdomain %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this company", company, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this company', edit_company_path(company), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company, class: "contents") do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation" class="px-3 py-2 mt-3 font-medium text-red-500 rounded-lg bg-red-50">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :plan %>
    <%= form.text_field :plan, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :employees_count %>
    <%= form.number_field :employees_count, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :website %>
    <%= form.text_field :website, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :location %>
    <%= form.text_field :location, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :hidden %>
    <%= form.check_box :hidden, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :currency %>
    <%= form.text_field :currency, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :subdomain %>
    <%= form.text_field :subdomain, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">Editing company</h1>

  <%= render "form", company: @company %>

  <%= link_to "Show this company", @company, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to companies", companies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/companies/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold">Companies</h1>
    <%= link_to 'New company', new_company_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="companies" class="relative min-w-full overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3">
            Name
          </th>
          <th scope="col" class="px-6 py-3">
            Plan
          </th>
          <th scope="col" class="px-6 py-3">
            Jobs
          </th>
          <th scope="col" class="px-6 py-3">
            Candidates
          </th>
          <th scope="col" class="px-6 py-3">
            Job Applications
          </th>
          <th scope="col" class="px-6 py-3">
            Tickets
          </th>
          <th scope="col" class="px-6 py-3">
            Status
          </th>
          <th scope="col" class="px-6 py-3">
            Edit
          </th>
        </tr>
      </thead>
      <tbody>
        <% @companies.each do |company| %>
          <tr class="bg-white border-b hover:bg-gray-50 hover:cursor-pointer">
            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap ">
              <%= company.name %>
            </th>
            <td class="px-6 py-4">
              <%= company.plan %>
            </td>
            <td class="px-6 py-4">
              <%= link_to jobs_path do %>
                <%= company.jobs.count %>
              <% end %>
            </td>
            <td class="px-6 py-4">
              <%= company.candidates.count %>
            </td>
            <td class="px-6 py-4">
              <%= company.job_applications.count %>
            </td>
            <td class="px-6 py-4">
              <%= company.tickets.count %>
            </td>
            <td class="px-6 py-4">
              <%= company.hidden ? 'Hidden' : 'Visible' %>
            </td>
            <td class="px-6 py-4">
              <%= link_to 'Edit', edit_company_path(company), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/companies/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">New company</h1>

  <%= render "form", company: @company %>

  <%= link_to 'Back to companies', companies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/companies/show.html.erb
<div class="flex w-full mx-auto md:w-2/3">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
    <% end %>

    <% @company.jobs.each do |job| %>
      <%= job.title %>
    <% end %>

    <%= link_to 'Edit this company', edit_company_path(@company), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this company', company_path(@company), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to companies', companies_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>