config/routes.rb
Rails.application.routes.draw do
  get 'recruiters/index'
  get 'recruiters/show'
  get 'candidates/index'
  devise_for :admins
  devise_for :recruiters
  devise_for :candidates

  resources :candidates
  resources :companies
  resources :jobs
  resources :job_applications
  resources :notes
  resources :recruiters
  resources :tickets

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  attr_accessor :is_dummy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_tenant :company
  has_one_attached :avatar
  has_many :job_applications, dependent: :destroy
  has_many :notes
  validates :email, :first_name, :last_name, :gender, :phone, :dob, :location, :nationality, :bio, :title, :linkedin, presence: true
  after_commit :set_avatar, on: [:create, :update]

  private
  def set_avatar
    unless avatar.attached? || is_dummy
      image = File.open(Rails.root.join("app", "assets", "images", "avatar.png"))
      avatar.attach(io: image, filename: "avatar.png" , content_type: "image/png")
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  attr_accessor :is_dummy
  has_many :jobs, dependent: :destroy
  has_many :job_applications, dependent: :destroy
  has_many :recruiters, dependent: :destroy
  has_many :candidates, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_one_attached :avatar
  validates :name, :employees_count, :website, :location, :currency, presence: true
  after_commit :set_avatar, on: [:create, :update]

  private
  def set_avatar
    unless avatar.attached? || is_dummy
      image = File.open(Rails.root.join("app", "assets", "images", "avatar.png"))
      avatar.attach(io: image, filename: "avatar.png" , content_type: "image/png")
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  acts_as_tenant :company
  belongs_to :recruiter, optional: true
  has_many :candidates, through: :job_applications
  has_many :job_applications, dependent: :destroy
  validates :title, :salary, :employment_type, :location, :role_description, :requirements, :benefits, :interview_process, presence: true
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  acts_as_tenant :company
  belongs_to :candidate
  belongs_to :job
  belongs_to :recruiter, optional: true
end

app/models/note.rb
class Note < ApplicationRecord
  acts_as_tenant :company
  belongs_to :candidate
  belongs_to :recruiter
  validates :body, presence: true
end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_tenant :company
  has_one_attached :avatar
  has_many :jobs
  has_many :job_applications
  has_many :notes, dependent: :destroy
  has_many :tickets, dependent: :destroy
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  acts_as_tenant :company
  belongs_to :recruiter
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :salary, :employment_type, :location, :role_description, :requirements, :benefits, :interview_process, :contact, :expiry_date, :status, :searchable, :recruiter_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:body, :recruiter_id, :candidate_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Opus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <div>
    <% if admin_signed_in? %>
    You're logged as an admin.
    <% elsif candidate_signed_in? %>
    You're logged as a candidate_id
    <% elsif recruiter_signed_in? %>
    You're logged as a recruiter
    <% end %>
  </div>
  <body>
    <main class="container flex px-5 mx-auto mt-28">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <h1 class="mb-6 text-4xl font-bold">Pages#home</h1>
  <h3 class="mb-4 text-xl font-semibold">Login</h3>
  <ul class="flex space-x-4">
    <li><%= link_to "As an Admin", new_admin_session_path, class:'btn-light' %></li>
    <li><%= link_to "As a Recruiter", new_recruiter_session_path, class:'btn-light' %></li>
    <li><%= link_to "As a Candidate", new_candidate_session_path, class:'btn-light' %></li>
  </ul>

  <h3 class="mt-10 mb-2 text-xl font-semibold">Resources by sudbomain</h3>
  <div id="companies" class="relative min-w-full overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3">
            Company
          </th>
          <th scope="col" class="px-6 py-3">
            Subdomain
          </th>
          <th scope="col" class="px-6 py-3">
            Recruiters
          </th>
          <th scope="col" class="px-6 py-3">
            Jobs
          </th>
          <th scope="col" class="px-6 py-3">
            Candidates
          </th>
          <th scope="col" class="px-6 py-3">
            Applications
          </th>
          <th scope="col" class="px-6 py-3">
            Notes
          </th>
          <th scope="col" class="px-6 py-3">
            Tickets
          </th>
          <th scope="col" class="px-6 py-3">
            Plan
          </th>
          <th scope="col" class="px-6 py-3">
            Status
          </th>
          <th scope="col" class="px-6 py-3 text-center">
            Edit
          </th>
        </tr>
      </thead>
      <tbody>
        <%  Company.all.each do |company|  %>
          <tr class="bg-white border-b hover:bg-gray-50 hover:cursor-pointer">
            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap ">
              <%= company.name %>
            </th>
            <th scope="row" class="px-6 py-4 font-mono text-xs font-normal text-fuchsia-700 whitespace-nowrap ">
              <%= company.subdomain %>
            </th>
            <td class="px-6 py-4 text-center">
              <%= link_to company.recruiters.count, "http://#{company.subdomain}.lvh.me:3000/recruiters" %>
            </td>
            <td class="px-6 py-4 text-center">
              <%= link_to company.jobs.count, "http://#{company.subdomain}.lvh.me:3000/jobs" %>
            </td>
            <td class="px-6 py-4 text-center">
              <%= link_to company.candidates.count, "http://#{company.subdomain}.lvh.me:3000/candidates" %>
            </td>
            <td class="px-6 py-4 text-center">
              <%= link_to company.job_applications.count, "http://#{company.subdomain}.lvh.me:3000/job_applications" %>
            </td>
            <td class="px-6 py-4 text-center">
              <%= link_to company.notes.count, "http://#{company.subdomain}.lvh.me:3000/notes" %>
            </td>
            <td class="px-6 py-4 text-center">
              <%= link_to company.tickets.count, "http://#{company.subdomain}.lvh.me:3000/tickets" %>
            </td>
            <td class="px-6 py-4">
              <%= company.plan %>
            </td>
            <td class="px-6 py-4">
              <%= company.hidden ? 'Hidden' : 'Visible' %>
            </td>
            <td class="px-6 py-4">
              <%= link_to 'Edit', edit_company_path(company), class: "btn-light" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>